### ISSUE TITLE
ioctl contract test's --with-arguments cannot handle param without name

### ISSUE THREAD

**Issue by raullenchai** [iotexproject/iotex-core#2512]
```
- constant: true
  inputs:
    - internalType: bytes32
      name: ''
      type: bytes32
  name: commitments
  outputs:
    - internalType: bool
      name: ''
      type: bool
  payable: false
  stateMutability: view
  type: function
```

`ioctl contract test function xxxx abc.abi commitments --with-arguments '{"":"b21b78b009d7ebcbc88f9d8986fa199a561b6d6a"}'` won't work.

Let's use `_` when the param name is empty, e.g., 
`ioctl contract test function xxxx abc.abi commitments --with-arguments '{"_":"b21b78b009d7ebcbc88f9d8986fa199a561b6d6a"}'` should work
